name: Release build

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

env:
  GO_VERSION: 1.17.3

jobs:
  main:
    name: Release build
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: build release for all architectures
        run: SKIP_VERSION_CHECK=1 make release tag=${{ env.RELEASE_VERSION }}

      - name: Create Release
        uses: lightninglabs/gh-actions/action-gh-release@2021.01.25.00
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: release ${{ env.RELEASE_VERSION }}
          draft: true
          prerelease: false
          files: release-${{ env.RELEASE_VERSION }}/*
          body: |

            Version: ${{ env.RELEASE_VERSION }}
            Golang version: `go${{ env.GO_VERSION }}`

            ⚡️⚡️⚡️ OK, now to the rest of the release notes! ⚡️⚡️⚡️

            # Release Notes

            TODO

            # Contributors (Alphabetical Order)

            TODO
